import C2 from "../assets/cards/2-C.png"
import C3 from "../assets/cards/3-C.png"
import C4 from "../assets/cards/4-C.png"
import C5 from "../assets/cards/5-C.png"
import C6 from "../assets/cards/6-C.png"
import C7 from "../assets/cards/7-C.png"
import C8 from "../assets/cards/8-C.png"
import C9 from "../assets/cards/9-C.png"
import C10 from "../assets/cards/10-C.png"
import CJ from "../assets/cards/J-C.png"
import CK from "../assets/cards/K-C.png"
import CQ from "../assets/cards/Q-C.png"
import CA from "../assets/cards/A-C.png"
import D2 from "../assets/cards/2-D.png"
import D3 from "../assets/cards/3-D.png"
import D4 from "../assets/cards/4-D.png"
import D5 from "../assets/cards/5-D.png"
import D6 from "../assets/cards/6-D.png"
import D7 from "../assets/cards/7-D.png"
import D8 from "../assets/cards/8-D.png"
import D9 from "../assets/cards/9-D.png"
import D10 from "../assets/cards/10-D.png"
import DJ from "../assets/cards/J-D.png"
import DK from "../assets/cards/K-C.png"
import DQ from "../assets/cards/Q-C.png"
import DA from "../assets/cards/A-C.png"
import H2 from "../assets/cards/2-H.png"
import H3 from "../assets/cards/3-H.png"
import H4 from "../assets/cards/4-H.png"
import H5 from "../assets/cards/5-H.png"
import H6 from "../assets/cards/6-H.png"
import H7 from "../assets/cards/7-H.png"
import H8 from "../assets/cards/8-H.png"
import H9 from "../assets/cards/9-H.png"
import H10 from "../assets/cards/10-H.png"
import HJ from "../assets/cards/J-H.png"
import HK from "../assets/cards/K-H.png"
import HQ from "../assets/cards/Q-H.png"
import HA from "../assets/cards/A-H.png"
import S2 from "../assets/cards/2-S.png"
import S3 from "../assets/cards/3-S.png"
import S4 from "../assets/cards/4-S.png"
import S5 from "../assets/cards/5-S.png"
import S6 from "../assets/cards/6-S.png"
import S7 from "../assets/cards/7-S.png"
import S8 from "../assets/cards/8-S.png"
import S9 from "../assets/cards/9-S.png"
import S10 from "../assets/cards/10-S.png"
import SJ from "../assets/cards/J-S.png"
import SK from "../assets/cards/K-S.png"
import SQ from "../assets/cards/Q-S.png"
import SA from "../assets/cards/A-S.png"





export default {C2, C3, C4, C5, C6, C7, C8, C9, C10, CJ, CK ,CQ, CA, D2, D3, D4, D5, 
D6, D7, D8, D9, D10, DJ, DK, DQ, DA, H2, H3, H4, H5, H6, H7, H8, H9, H10, HJ, 
HK, HQ, HA, S2, S3, S4, S5, S6, S7, S8, S9, S10, SJ, SK, SQ, SA};
